#include "scripts\base.inc"

// here comes the stuff which initializes the scene

actor.X = 46;
actor.Y = 497;

actor.Direction = DI_RIGHT;
actor.Active = true;


////////////////////////////////////////////////////////////////////////////////
// scene state
global Statecalabozo2;


// default values
if(Statecalabozo2==null)
{
  Statecalabozo2.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!Statecalabozo2.Visited)
{
  Statecalabozo2.Visited = true;

  // this is our first visit in this scene...
}

