#include "scripts\base.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(99, 512);
actor.Direction = DI_RIGHT;
actor.Active = true;

actor.GoTo(99, 512);
actor.TurnTo(DI_RIGHT);

////////////////////////////////////////////////////////////////////////////////
// scene state
global Statecalabozo2;


// default values
if(Statecalabozo2==null)
{
  Statecalabozo2.Visited = false;
  Game.PlayMusic("music\calabozo.ogg");
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!Statecalabozo2.Visited)
{
  Statecalabozo2.Visited = true;

  // this is our first visit in this scene...
}

