#include "scripts\base.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(132, 596);
actor.Direction = DI_RIGHT;
actor.Active = true;


////////////////////////////////////////////////////////////////////////////////
// scene state
global Statemapa;


// default values
if(Statemapa==null)
{
  Statemapa.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!Statemapa.Visited)
{
  Statemapa.Visited = true;

  // this is our first visit in this scene...
}

