#include "scripts\base.inc"

// here comes the stuff which initializes the scene



////////////////////////////////////////////////////////////////////////////////
// scene state
global Stateddp_logo;

Game.PlayMusic("data/scenes/intro/SB Demo 3 - An Icy Planet.ogg");

// default values
if(Stateddp_logo==null)
{
  Stateddp_logo.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!Stateddp_logo.Visited)
{
  Stateddp_logo.Visited = true;

  // this is our first visit in this scene...
}

Sleep(7000);
Game.Interactive = true;

Game.ChangeScene("scenes/calabozo/calabozo.scene");

