#include "scripts\base.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(214, 612);
actor.Direction = DI_RIGHT;
actor.Active = true;


////////////////////////////////////////////////////////////////////////////////
// scene state
global Statecontaduria;


// default values
if(Statecontaduria==null)
{
  Statecontaduria.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!Statecontaduria.Visited)
{
  Statecontaduria.Visited = true;

  // this is our first visit in this scene...
}

