#include "scripts\base.inc"

var Libro = Scene.GetNode("libro");
global EstadoLibro;

if(EstadoLibro==null)
{
  EstadoLibro.yaIntentado = false;
}


////////////////////////////////////////////////////////////////////////////////
on "LookAt"
{
  actor.GoToObject(this);
  actor.Talk("Uh...Los versos del chancho!");
}


////////////////////////////////////////////////////////////////////////////////
on "Take"
{
  actor.GoToObject(this);
  
  if (EstadoLibro.yaIntentado == false) {
	EstadoLibro.yaIntentado = true;
  	actor.Talk("No voy a agarrar esto. Podría caerse mi mano.");
	actor.Talk("SON LAS MEMORIAS DEL CHANCHO EN INGLES");
  } else {
    Game.TakeItem("libro");
    Libro.Active = false;
  }
}


////////////////////////////////////////////////////////////////////////////////
on "Talk"
{
  actor.GoToObject(this);
  actor.Talk("Hablar con un libro no es muy lógico. ¿No te parece?");
}


////////////////////////////////////////////////////////////////////////////////
on "LeftClick"
{
  actor.GoToObject(this);
}
